title: Jyoti Prakash - Personal Website
email: jyotiprakash1@acm.org
heading: Dr. Jyoti Prakash
subheading: Assistant Professor @ Maersk Mc-Kinney Moller Institute, University of Southern Denmark
github: https://github.com/jpksh90
linkedin: https://www.linkedin.com/in/jprakash90/
twitter: https://twitter.com/jpksh90
google_scholar: https://scholar.google.de/citations?user=-hJIVcwAAAAJ

pages: ["index", "publications", "research", "teaching_service"]
photo_credit: "ankitarout_23"
