title: Jyoti Prakash - Personal Website
email: jyotiprakash1@acm.org
heading: Jyoti Prakash
github: https://github.com/jpksh90
linkedin: https://www.linkedin.com/in/jprakash90/
twitter: https://twitter.com/jpksh90
google_scholar: https://scholar.google.de/citations?user=-hJIVcwAAAAJ

pages: {index: "about", research: "research", publications_talks: "publications & talks",  teaching: "teaching", service: "service"}
# photo_credit: "ankitarout_23"

# Path to profile photo (relative to docs/ or static root)
photo_path: "../docs/images/Photo-Indian-Passport.jpg"
